### ISSUE TITLE
Non-ASCII characters in storage directory path

### ISSUE THREAD

**Issue by paszklar** [cppan/cppan#15]
cppan doesn't seem to handle non-ascii characters in storage_dir path correctly. Running it with:

    storage_dir: D:\Libraries\cppan-storage

in `cppan.yml` doesn't cause any issues, but changing it to:

    storage_dir: D:\Libraries\cppąń-storage

produces the following error:

    C:\>cppan
    Can't open database file: D:/Libraries\cpp╣˝-storage\etc\database\service.db error: unable to open database file

I'm running 64-bit Windows 10 Education N Version 1607

Edit: Also having non-ascii characters in TEMP path causes build process to fail

**Comment by egorpugin** [comment]
Hi,
Yes, this is a known issue, please use only latin letters for the moment.

**Comment by yuangu** [comment]
Chinese characters also have this kind of problem

**Comment by egorpugin** [comment]
I've implemented unicode dir and file names handling, so update you cppan client via `cppan --self-upgrade` or from website and try it.

ps.
It does not work for me completely because ninja cannot handle unicode paths and also when trying to build with `cmake --build .`, for example, with visual studio. But on cppan side everything should work.

**Comment by egorpugin** [comment]
Marking this as fixed, please, comment if you still have unicode path issues.
