### ISSUE TITLE
Could you update pvt.cppan.demo.martinmoene.gsl_lite?

### ISSUE THREAD

**Issue by biocomp** [cppan/cppan#34]
Or what is the process of updating the package myself? The library is not mine.

**Comment by egorpugin** [comment]
Done.

You also can add package to your namespace (or ask author to add his library himself).
To do it youself:
1. Go to cppan.org
2. Add -> Add Package
3. If you need `martinmoene` directory - select Type: Directory, add it
4. Otherwise add library with name gsl_lite
5. Go to it (Children button)
6. Add version from git or from specification (cppan. yml spec - copy spec from https://cppan.org/pvt.cppan.demo.martinmoene.gsl_lite/version/0.25.0/specification).

**Comment by biocomp** [comment]
Thanks! :)
